spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:mem:ais
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Automatic Irrigation Scheduler Configuration
ais:
  jobs:
    auto-irrigation:
      enabled: true
      fixed-delay: 10000
      initial-delay: 1000
      retry:
        count: 3
        intervalInMillis: 10000
    slot-schedule:
      enabled: true
      fixed-delay: 10000
      initial-delay: 1000

springdoc:
  api-docs:
    path: /api-docs

flyway:
  locations: classpath:resources/db/migration
  enabled: true